routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\SignUpController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Teamwork\AuthController;
use App\Http\Controllers\Teamwork\TeamController;
use App\Http\Controllers\Admin\AdminPlanController;
use App\Http\Controllers\Teamwork\TeamRoleController;
use App\Http\Controllers\Admin\AdminPaymentController;
use App\Http\Controllers\Teamwork\TeamMemberController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\RoleController as AdminRoleController;
use App\Http\Controllers\Admin\PermissionController as AdminPermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::view('dashboard', 'dashboard')
	->name('dashboard')
	->middleware(['auth', 'verified']);

// Route::get('/profile/user', function () {
//     return view('profile.show');
// })->name('profile.show');

// Route::resource('user', ProfileController::class);

Route::get('/signup', [SignUpController::class, 'index'])->name('signup');
Route::group(['middleware' => ['auth'],'prefix' => 'signup'],function () {

    Route::get('/review/{id}', [SignUpController::class, 'review'])->name('signup.review');
    Route::get('/pay/{payment_link}', [SignUpController::class, 'pay'])->name('signup.pay');
    Route::post('/go/{payment_gateway}', [SignUpController::class, 'go'])->name('signup.go');
    Route::post('/thankyou/{payment_gateway}', [SignUpController::class, 'thankyou'])->name('signup.thankyou');
    Route::get('/thankyou/{payment_gateway}', [SignUpController::class, 'thankyou']);
    Route::get('/callback/{payment_gateway}', [SignUpController::class, 'callback'])->name('signup.callback');
    Route::post('/callback/{payment_gateway}', [SignUpController::class, 'callback']);


});

// Regular users
Route::group(['middleware' => ['auth'],'prefix' => 'users'], function () {

    Route::get('/profile/{user}', [ProfileController::class, 'show'])->name('user-profile.show');
    Route::put('/profile/{user}/edit', [ProfileController::class, 'update'])->name('user-profile.update');

    Route::resource('plans', PlanController::class);
    Route::resource('payment', PaymentController::class);
});


/**
 * Admin routes
 */
Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' =>'admin.'], function () {

    Route::resource('plans', AdminPlanController::class);
    Route::resource('users', AdminUserController::class);

    Route::resource('roles', AdminRoleController::class);
    Route::resource('permissions', AdminPermissionController::class);
});


/**
 * Teamwork Roles & Permission routes
 */
Route::group(['middleware' => ['auth'], 'prefix' => 'teams', 'as' => 'teams.'], function ()
{
    Route::resource('roles', TeamRoleController::class);
    Route::resource('permissions', TeamRoleController::class);
});

/**
 * Teamwork routes
 */
Route::group(['middleware' => ['auth'], 'prefix' => 'teams', 'namespace' => 'Teamwork'], function()
{
    Route::get('/', [TeamController::class, 'index'])->name('teams.index');
    Route::get('create', [TeamController::class, 'create'])->name('teams.create');
    Route::get('/{id}', [TeamController::class, 'show'])->name('teams.show')->can('update');
    Route::post('teams', [TeamController::class, 'store'])->name('teams.store');
    Route::get('edit/{id}', [TeamController::class, 'edit'])->name('teams.edit')->can('update');
    Route::put('edit/{id}', [TeamController::class, 'update'])->name('teams.update')->can('update');
    Route::delete('destroy/{id}', [TeamController::class, 'destroy'])->name('teams.destroy')->can('delete');
    Route::get('switch/{id}', [TeamController::class, 'switchTeam'])->name('teams.switch');

    Route::get('members/{id}', [TeamMemberController::class, 'show'])->name('teams.members.show');
    Route::get('members/resend/{invite_id}', [TeamMemberController::class, 'resendInvite'])->name('teams.members.resend_invite');
    Route::post('members/{id}', [TeamMemberController::class, 'invite'])->name('teams.members.invite');
    Route::delete('members/{id}/{user_id}', [TeamMemberController::class, 'destroy'])->name('teams.members.destroy');

    Route::get('accept/{token}', [AuthController::class, 'acceptInvite'])->name('teams.accept_invite');
});

app/Models/Role.php
<?php

namespace App\Models;

use Spatie\Permission\Models\Role as SpatieRole;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Role extends SpatieRole
{
    use HasFactory;
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Role;
use App\Models\Permission;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use App\Http\Requests\StoreRoleRequest;
use App\Http\Requests\UpdateRoleRequest;

class RoleController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('is super admin'))
        {
            return abort(403);
        }
        $roles = Role::all();
        // $team = Team::findOrFail(auth()->user()->current_team_id);

        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('is super admin'))
        {
            return abort(403);
        }
        $permissions = Permission::get()->pluck('name','name');

        return view('admin.roles.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRoleRequest $request)
    {
        if (! Gate::allows('is super admin'))
        {
            return abort(403);
        }

        $role = Role::create($request->except('permission'));
        $permissions = $request->input('permission') ? $request->input('permission') : [];
        $role->givePermissionTo($permissions);

        return redirect()->route('admin.roles.index')->with('success', "The role <b>$role->name</b> successfully created!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        if (! Gate::allows('is super admin'))
        {
            return abort(403);
        }

        $role->load('permissions');
        $permissions = Permission::get()->pluck('name','name');

        return view('admin.roles.show', compact('role', 'permissions'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        if (! Gate::allows('is super admin'))
        {
            return abort(403);
        }
        $permissions = Permission::get()->pluck('name','name');

        // dd($role, $permissions);
        return view('admin.roles.show', compact('role','permissions'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRoleRequest $request, Role $role)
    {
        if (! Gate::allows('is super admin'))
        {
            return abort(403);
        }

        $role->update($request->except('permissions'));
        $permissions = $request->input('permission') ? $request->input('permission') : [];
        $role->syncPermissions($permissions);
        // $team->updateRoleOfTeam($team,$request->role_id);

        return redirect()->route('admin.roles.index')->with('success', "The role <b>$role->name</b> successfully updated!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        if (! Gate::allows('is super admin'))
        {
            return abort(403);
        }

        $role->delete();

        return redirect()->route('admin.roles.index')->with('success', "The role <b>$role->name</b> successfully deleted!");
    }

    /**
     * Delete all selected Role at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        Role::whereIn('id', request('ids'))->delete();

        return response()->noContent();
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.private',[
'activePage' => 'roleCreate',
'parentPage' => 'Role',
'menuParent' => 'admin.roles.index',
'title' => __('Create Roles')
])

@section('content')
<div class="container-fluid py-4">
    <div class="row mt-4">
        <div class="col-lg-9 col-12 mx-auto position-relative">
            <div class="card">
                <div class="card-header p-3 pt-2">
                    <div
                        class="icon icon-lg icon-shape bg-gradient-success shadow text-center border-radius-xl mt-n4 me-3 float-start">
                        <i class="material-icons opacity-10">groups</i>
                    </div>
                    <h6 class="mb-0">{{__('Create Role')}}</h6>
                </div>
                <div class="card-body pt-2">
                    <form class="form-horizontal" method="post" action="{{route('admin.roles.store')}}">
                        @csrf
                        <div class="form-group @error('name') has-error text-danger @enderror">
                            <div class="input-group input-group-static">
                                <label for="roleName">{{__('Role Name')}}</label>
                                <input type="text" class="form-control" id="roleName" name="name"
                                    value="{{ old('name') }}">
                                @error('name')
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="d-flex justify-content-end mt-4">
                            {{-- <button type="button" name="button" class="btn btn-light m-0" href=""></button> --}}
                            <a href="{{route('admin.roles.index')}}" class="btn btn-light m-0">{{__('Cancel')}}</a>
                            <button type="Submit" name="button" class="btn bg-gradient-success m-0 ms-2">{{__('Create
                                Role')}}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {{-- @include('layouts.footers.auth') --}}
</div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.private',[
'activePage' => 'roleIndex',
'parentPage' => 'Role',
'menuParent' => '',
'title' => __('Roles')
])
@section('content')
<div class="container-fluid py-4">
    <section class="py-3">
        @if( session('success') )
        @include('layouts.alerts.feedback')
        @endif
        <div class="row mb-4 mb-md-0">
            <div class="col-md-8 me-auto my-auto text-left">
                <h5>List of All Your Roles</h5>
                <p>You can see all your roles here. <br> You may edit, view role from this page.</p>

            </div>
            <div class="col-lg-4 col-md-12 my-auto text-end">
                {{-- <button type="button" class="btn bg-gradient-primary mb-0 mt-0 mt-md-n9 mt-lg-0"
                    href="{{route('admin.roles.create')}}">

                </button> --}}
                <a href="{{route('admin.roles.create')}}" class="btn bg-gradient-warning mb-0 mt-0 mt-md-n9 mt-lg-0">
                    <i class="material-icons text-white position-relative text-md pe-2">add</i>{{__('Create
                    Role')}}
                </a>
            </div>
        </div>
        <div class="card shadow mt-lg-4 mb-4">
            {{-- <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">{{__('List Of Roles')}}</h6>
            </div> --}}
            <div class="card-body">
                <table class="table table-stripe">
                    <thead>
                        <tr>
                            <th class="text-center">ID</th>
                            <th class="text-center">NAME</th>
                            <th class="text-center">PERMISSIONS</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($roles as $role)
                        <tr>
                            <td class="text-center">{{$role->id}}</td>
                            <td class="text-center">{{$role->name}}</td>
                            <td class="text-center text-sm">@foreach ($role->permissions()->pluck('name')
                                as $permission)
                                <span class="badge badge-info">{{ $permission }}</span><br />
                                @endforeach
                            </td>
                            <td>
                                <a href="{{ route('admin.roles.edit', $role->id) }}"
                                    class="btn btn-sm btn-secondary">EDIT</a>

                                <form method="post" class="d-inline"
                                    action="{{ route('admin.roles.destroy', $role->id) }}"
                                    onsubmit="return confirm('Are you sure you want to delete {{$role->name}} ({{$role->id}})?');">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm">DELETE</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>

                </table>
            </div>
        </div>
    </section>
    @include('layouts.footers.auth')
    <div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modal-delete"
        aria-hidden="true">
        <div class="modal-dialog modal-danger modal-dialog-centered modal-" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h6 class="modal-title font-weight-normal" id="modal-title-delete">{{__('Delete Roles')}}
                    </h6>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="py-3 text-center">
                        <i class="material-icons h1 text-secondary">
                            notifications_active
                        </i>
                        <h5 class="text-gradient text-danger mt-4">Are you sure you want to delete this
                            {{$role->name}}
                            record?</h5>
                        <p>If you delete this, it will be gone forever.
                        </p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link text-secondary "
                        data-bs-dismiss="modal">{{__('Cancel')}}</button>
                    <form action="{{route('admin.roles.destroy', $role)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <input type="hidden" name="_method" value="DELETE" />
                        <button type="submit" class="btn btn-success ml-auto">{{__('Yes,
                            Delete It')}}</button>
                        {{-- <button class="btn btn-danger btn-sm">
                            Delete</button> --}}
                        {{-- <a class="dropdown-item" href="javascript:;"
                            onclick="material.showSwal('warning-message-and-confirmation')"><i
                                class="fa fa-trash-o"></i>
                            {{__('Delete')}} --}}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/show.blade.php
@extends('layouts.private',[
'activePage' => 'roleEdit',
'parentPage' => 'Role',
'menuParent' => 'admin.roles.index',
'title' => __('Roles')
])

@section('content')
<div class="container-fluid py-4">
    <div class="row mt-4">
        <div class="col-lg-9 col-12 mx-auto position-relative">
            <div class="card">
                <div class="card-header p-3 pt-2">
                    <div
                        class="icon icon-lg icon-shape bg-gradient-success shadow text-center border-radius-xl mt-n4 me-3 float-start">
                        <i class="material-icons opacity-10">groups</i>
                    </div>
                    <h6 class="mb-0">{{__('Edit Roles')}} {{$role->name}}</h6>
                </div>
                <div class="card-body pt-2">
                    <form class="form-horizontal" method="post" action="
                    {{route('admin.roles.update', $role)}}
                    ">
                        @method('PUT')
                        @csrf
                        <div class="form-group @error('name') has-error text-danger @enderror">
                            <div class="input-group input-group-static">
                                <label for="roleName">{{__('Roles Name')}}</label>
                                <br />
                                <input type="text" class="form-control" id="roleName" name="name"
                                    placeholder="{{ old('name', $role->name) }}" value="{{ old('name', $role->name) }}">
                                @error('name')
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group {{ $errors->has('permission') ? 'has-error' : '' }}">
                            {{-- <label for="permission">{{__('Roles Name')}}*
                                <span class="btn btn-info btn-xs select-all">{{__('Select All')}}</span>
                                <span class="btn btn-info btn-xs deselect-all">{{__('Deselect All')}}</span></label>
                            <select name="permission[]" id="permission" class="form-control select2" multiple="multiple"
                                required>
                                @foreach($permissions as $id => $permissions)
                                <option value="{{ $id }}" {{ (in_array($id, old('permissions', [])) || isset($role) &&
                                    $role->permissions()->pluck('name', 'id')->contains($id)) ? 'selected' : '' }}>{{
                                    $permissions }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('permission'))
                            <em class="invalid-feedback">
                                {{ $errors->first('permission') }}
                            </em>
                            @endif --}}
                            <div class="custom-control custom-checkbox small mt-4">
                                <h6>{{__('Permissions')}}</h6>
                                @foreach($permissions as $id => $permissions)
                                <input @if( in_array($id, old('permissions', [])) || isset($role) &&
                                    $role->permissions()->pluck('name', 'id')->contains($id))
                                checked
                                @endif
                                type="checkbox" class="custom-control-input"
                                name="permission[]" value="{{$permissions}}" id="permission_{{$permissions}}">
                                <label class="custom-control-label"
                                    for="permission_{{$permissions}}">{{$permissions}}</label><br />
                                @endforeach
                            </div>
                        </div>

                        <div class="d-flex justify-content-end mt-4">
                            <a href="{{route('admin.roles.index', $role)}}"
                                class="btn btn-light m-0">{{__('Cancel')}}</a>
                            <button type="Submit" name="button" class="btn bg-gradient-success m-0 ms-2"><i
                                    class="fa fa-btn fa-save"></i> {{__('Save')}}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {{-- @include('layouts.footers.auth') --}}
</div>
@endsection