routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\SignUpController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Teamwork\AuthController;
use App\Http\Controllers\Teamwork\TeamController;
use App\Http\Controllers\Admin\AdminPlanController;
use App\Http\Controllers\Teamwork\TeamRoleController;
use App\Http\Controllers\Admin\AdminPaymentController;
use App\Http\Controllers\Teamwork\TeamMemberController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\RoleController as AdminRoleController;
use App\Http\Controllers\Admin\PermissionController as AdminPermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::view('dashboard', 'dashboard')
	->name('dashboard')
	->middleware(['auth', 'verified']);

// Route::get('/profile/user', function () {
//     return view('profile.show');
// })->name('profile.show');

// Route::resource('user', ProfileController::class);

Route::get('/signup', [SignUpController::class, 'index'])->name('signup');
Route::group(['middleware' => ['auth'],'prefix' => 'signup'],function () {

    Route::get('/review/{id}', [SignUpController::class, 'review'])->name('signup.review');
    Route::get('/pay/{payment_link}', [SignUpController::class, 'pay'])->name('signup.pay');
    Route::post('/go/{payment_gateway}', [SignUpController::class, 'go'])->name('signup.go');
    Route::post('/thankyou/{payment_gateway}', [SignUpController::class, 'thankyou'])->name('signup.thankyou');
    Route::get('/thankyou/{payment_gateway}', [SignUpController::class, 'thankyou']);
    Route::get('/callback/{payment_gateway}', [SignUpController::class, 'callback'])->name('signup.callback');
    Route::post('/callback/{payment_gateway}', [SignUpController::class, 'callback']);


});

// Regular users
Route::group(['middleware' => ['auth'],'prefix' => 'users'], function () {

    Route::get('/profile/{user}', [ProfileController::class, 'show'])->name('user-profile.show');
    Route::put('/profile/{user}/edit', [ProfileController::class, 'update'])->name('user-profile.update');

    Route::resource('plans', PlanController::class);
    Route::resource('payment', PaymentController::class);
});


/**
 * Admin routes
 */
Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' =>'admin.'], function () {

    Route::resource('plans', AdminPlanController::class);
    Route::resource('users', AdminUserController::class);

    Route::resource('roles', AdminRoleController::class);
    Route::resource('permissions', AdminPermissionController::class);
});


/**
 * Teamwork Roles & Permission routes
 */
Route::group(['middleware' => ['auth'], 'prefix' => 'teams', 'as' => 'teams.'], function ()
{
    Route::resource('roles', TeamRoleController::class);
    Route::resource('permissions', TeamRoleController::class);
});

/**
 * Teamwork routes
 */
Route::group(['middleware' => ['auth'], 'prefix' => 'teams', 'namespace' => 'Teamwork'], function()
{
    Route::get('/', [TeamController::class, 'index'])->name('teams.index');
    Route::get('create', [TeamController::class, 'create'])->name('teams.create');
    Route::get('/{id}', [TeamController::class, 'show'])->name('teams.show')->can('update');
    Route::post('teams', [TeamController::class, 'store'])->name('teams.store');
    Route::get('edit/{id}', [TeamController::class, 'edit'])->name('teams.edit')->can('update');
    Route::put('edit/{id}', [TeamController::class, 'update'])->name('teams.update')->can('update');
    Route::delete('destroy/{id}', [TeamController::class, 'destroy'])->name('teams.destroy')->can('delete');
    Route::get('switch/{id}', [TeamController::class, 'switchTeam'])->name('teams.switch');

    Route::get('members/{id}', [TeamMemberController::class, 'show'])->name('teams.members.show');
    Route::get('members/resend/{invite_id}', [TeamMemberController::class, 'resendInvite'])->name('teams.members.resend_invite');
    Route::post('members/{id}', [TeamMemberController::class, 'invite'])->name('teams.members.invite');
    Route::delete('members/{id}/{user_id}', [TeamMemberController::class, 'destroy'])->name('teams.members.destroy');

    Route::get('accept/{token}', [AuthController::class, 'acceptInvite'])->name('teams.accept_invite');
});

resources/views/layouts/navbars/navbar.blade.php
<!-- Navbar -->
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 border-radius-xl shadow-none" id="navbarBlur"
    data-scroll="false">
    <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                <li class="breadcrumb-item text-sm">
                    <a class="opacity-3 text-dark" href="{{route('dashboard')}}">
                        <svg width="12px" height="12px" class="mb-1" viewBox="0 0 45 40" version="1.1"
                            xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                            <title>shop </title>
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <g transform="translate(-1716.000000, -439.000000)" fill="#252f40" fill-rule="nonzero">
                                    <g transform="translate(1716.000000, 291.000000)">
                                        <g transform="translate(0.000000, 148.000000)">
                                            <path
                                                d="M46.7199583,10.7414583 L40.8449583,0.949791667 C40.4909749,0.360605034 39.8540131,0 39.1666667,0 L7.83333333,0 C7.1459869,0 6.50902508,0.360605034 6.15504167,0.949791667 L0.280041667,10.7414583 C0.0969176761,11.0460037 -1.23209662e-05,11.3946378 -1.23209662e-05,11.75 C-0.00758042603,16.0663731 3.48367543,19.5725301 7.80004167,19.5833333 L7.81570833,19.5833333 C9.75003686,19.5882688 11.6168794,18.8726691 13.0522917,17.5760417 C16.0171492,20.2556967 20.5292675,20.2556967 23.494125,17.5760417 C26.4604562,20.2616016 30.9794188,20.2616016 33.94575,17.5760417 C36.2421905,19.6477597 39.5441143,20.1708521 42.3684437,18.9103691 C45.1927731,17.649886 47.0084685,14.8428276 47.0000295,11.75 C47.0000295,11.3946378 46.9030823,11.0460037 46.7199583,10.7414583 Z">
                                            </path>
                                            <path
                                                d="M39.198,22.4912623 C37.3776246,22.4928106 35.5817531,22.0149171 33.951625,21.0951667 L33.92225,21.1107282 C31.1430221,22.6838032 27.9255001,22.9318916 24.9844167,21.7998837 C24.4750389,21.605469 23.9777983,21.3722567 23.4960833,21.1018359 L23.4745417,21.1129513 C20.6961809,22.6871153 17.4786145,22.9344611 14.5386667,21.7998837 C14.029926,21.6054643 13.533337,21.3722507 13.0522917,21.1018359 C11.4250962,22.0190609 9.63246555,22.4947009 7.81570833,22.4912623 C7.16510551,22.4842162 6.51607673,22.4173045 5.875,22.2911849 L5.875,44.7220845 C5.875,45.9498589 6.7517757,46.9451667 7.83333333,46.9451667 L19.5833333,46.9451667 L19.5833333,33.6066734 L27.4166667,33.6066734 L27.4166667,46.9451667 L39.1666667,46.9451667 C40.2482243,46.9451667 41.125,45.9498589 41.125,44.7220845 L41.125,22.2822926 C40.4887822,22.4116582 39.8442868,22.4815492 39.198,22.4912623 Z">
                                            </path>
                                        </g>
                                    </g>
                                </g>
                            </g>
                        </svg>
                    </a>
                </li>
                @if ($activePage == 'dashboard')

                <li class="breadcrumb-item text-sm text-dark active" aria-current="page">{{$title}}</li>
                @elseif ($menuParent != '')
                <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark"
                        href="{{route("$menuParent")}}">{{$parentPage}}</a>
                </li>
                <li class="breadcrumb-item text-sm text-dark active" aria-current="page">{{$title}}</li>
                @else
                <li class="breadcrumb-item text-sm text-dark active" aria-current="page">{{$title}}</li>
                @endif
            </ol>
            <h6 class="font-weight-bolder mb-0">{{$title}}</h6>
        </nav>
        <div class="sidenav-toggler sidenav-toggler-inner d-xl-block d-none ">
            <a href="javascript:;" class="nav-link text-body p-0">
                <div class="sidenav-toggler-inner">
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                </div>
            </a>
        </div>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
            <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                {{-- <div class="input-group input-group-outline">
                    <label class="form-label">Search here</label>
                    <input type="text" class="form-control">
                </div> --}}
            </div>
            <ul class="navbar-nav  justify-content-end ">
                <!-- Team Management -->
                @if (Auth::user()->teams->count() < 1) <li class="nav-item ">
                    <a class="nav-link {{ $activePage == 'teamCreate' ? 'text-white bg-gradient-success active' : 'text-dark' }}"
                        href="{{ route('teams.create') }}">
                        <i class="material-icons-round opacity-10">group_add</i>
                        <span class="nav-link-text ms-2 ps-1">{{ __('Create Team') }}</span>
                    </a>
                    </li>
                    @elseif (Auth::user()->currentTeam !== null)
                    <li class="nav-item dropdown pe-3 my-auto">
                        <a href="javascript:;" class="btn dropdown-toggle btn-sm my-auto position-relative btn-success"
                            id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">

                            {{ Auth::user()->currentTeam->name }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end p-2 me-sm-n4" aria-labelledby="dropdownMenuButton">
                            <li class="mb-2">
                                <a class="dropdown-item border-radius-md"
                                    href="{{ route('teams.show', Auth::user()->currentTeam->uuid) }}">
                                    <div class="d-flex align-items-center py-1">
                                        <span class="material-icons-round">
                                            manage_accounts
                                        </span>
                                        <div class="ms-2">
                                            <h6 class="text-sm font-weight-normal my-auto">
                                                {{ __('Team Settings') }}
                                            </h6>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="mb-2">
                                <a class="dropdown-item border-radius-md" href="{{ route('teams.create') }}">
                                    <div class="d-flex align-items-center py-1">
                                        <span class="material-icons-round">add_circle_outline</span>
                                        <div class="ms-2">
                                            <h6 class="text-sm font-weight-normal my-auto">
                                                {{ __('Create New Team') }}
                                            </h6>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="mb-2">
                                <a class="dropdown-item border-radius-md" href="{{ route('teams.index') }}">
                                    <div class="d-flex align-items-center py-1">
                                        <span class="material-icons-round">
                                            groups
                                        </span>
                                        <div class="ms-2">
                                            <h6 class="text-sm font-weight-normal my-auto">
                                                {{ __('List All Team') }}
                                            </h6>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li class="nav-item mt-3 mb-2">
                                <h6 class="ms-2 text-uppercase text-xs font-weight-bolder text-dark text-start">
                                    {{ __('Switch Team') }}</h6>
                            </li>
                            @foreach (Auth::user()->teams as $team)
                            <li class="mb-2">
                                <a class="dropdown-item border-radius-md {{ Auth::user()->current_team_id == $team->id ? 'bg-gradient-success' : '' }}"
                                    href="{{ route('teams.switch', $team->uuid) }}">
                                    <div class="d-flex align-items-center py-1">
                                        <span
                                            class="material-icons-round @if ($team->id == Auth::user()->current_team_id) text-white @endif">groups</span>
                                        <div class="ms-2">
                                            <h6
                                                class="text-sm font-weight-normal my-auto @if ($team->id == Auth::user()->current_team_id) text-white @endif">
                                                {{ $team->name }}
                                            </h6>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            @endforeach
                        </ul>
                    </li>
                    @endif
                    <!-- Account Management -->
                    <li class="nav-item dropdown pe-3 my-auto">
                        <a href="javascript:;" class="nav-link dropdown-toggle text-body p-0 position-relative"
                            id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ Auth::user()->name }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end p-2 me-sm-n4" aria-labelledby="dropdownMenuButton">
                            <li class="mb-2">
                                <a class="dropdown-item border-radius-md"
                                    href="{{ route('user-profile.show', Auth::user()->id) }}">
                                    <div class="d-flex align-items-center py-1">
                                        <span class="material-icons-round">
                                            face
                                        </span>
                                        <div class="ms-2">
                                            <h6 class="text-sm font-weight-normal my-auto">
                                                {{ __('Profile') }}
                                            </h6>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item border-radius-md" href="{{ route('logout') }}"
                                    onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    <div class="d-flex align-items-center py-1">
                                        <span class="material-icons">how_to_reg</span>
                                        <div class="ms-2">
                                            <h6 class="text-sm font-weight-normal my-auto">
                                                {{ __('Log out') }}
                                            </h6>
                                        </div>
                                    </div>
                                </a>
                                <form method="POST" id="logout-form" action="{{ route('logout') }}"
                                    style="display: none;">
                                    @csrf
                                    <input type="hidden" name="current_team_id">
                                    </a>
                                </form>
                            </li>
                        </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->

resources/views/layouts/navbars/sidebar.blade.php
<aside
    class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3 ps ps--active-y bg-white"
    id="sidenav-main" data-color="success">
    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer opacity-5 position-absolute end-0 top-0 d-xl-none text-dark"
            aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" href="{{ route('dashboard') }}">
            <img src="/logo-veegro.png" class="navbar-brand-img h-100" alt="main_logo">
            <span class="ms-1 font-weight-bold text-dark"></span>
        </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto h-auto max-height-vh-100 h-100" id="sidenav-collapse-main">
        <ul class="navbar-nav">
            <li class="nav-item mb-2 mt-0">
                <a data-bs-toggle="collapse" href="#ProfileNav" class="nav-link text-dark" aria-controls="ProfileNav"
                    role="button" {{ ($menuParent=='user' ) ? ' aria-expanded="true"' : ' aria-expanded="false"' }}>
                    {{-- <img class="rounded-circle" width="32" height="32" src="{{ Auth::user()->profile_photo_url }}"
                    class="avatar" alt="{{ Auth::user()->name }}"> --}}
                    <span class="material-icons-round opacity-10">
                        face
                    </span>
                    <span class="nav-link-text ms-2 ps-1">{{ Auth::user()->name }}</span>
                </a>
                <div class="collapse" id="ProfileNav" style="">
                    <ul class="nav ">
                        <li class="nav-item {{ $activePage == 'user_profile' ? 'active' : ''}}">
                            <a class="nav-link text-dark" href="{{ route('user-profile.show', Auth::user()->id) }}">
                                <i class="material-icons-round opacity-10">account_circle</i>
                                <span class="sidenav-normal  ms-3  ps-1">{{ __('My Profile') }}</span>
                            </a>
                        </li>
                        {{-- @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="{{ route('api-tokens.index') }}">
                        <span class="sidenav-mini-icon">{{ __('API') }}</span>
                        <span class="sidenav-normal  ms-3  ps-1">{{ __('API Tokens') }}</span>
                        </a>
            </li>
            @endif
            <li class="nav-item">
                <a class="nav-link text-dark " href="../../pages/pages/account/settings.html">
                    <span class="sidenav-mini-icon"> S </span>
                    <span class="sidenav-normal  ms-3  ps-1"> Settings </span>
                </a>
            </li> --}}
            <li class="nav-item">
                <a class="nav-link text-dark " href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                    <i class="material-icons-round opacity-10">logout</i>
                    <span class="sidenav-normal  ms-3  ps-1">{{ __('Log out') }}</span>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </a>
            </li>
        </ul>
    </div>
    </li>
    @can('is super admin')
    <hr class="horizontal dark mt-0">
    <li class="nav-item mt-3">
        <h6 class="ps-4  ms-2 text-uppercase text-xs font-weight-bolder text-dark">{{ __('ADMIN') }}</h6>
    </li>
    {{-- Admin Menu --}}
    <li class="nav-item {{ $parentPage == 'User' ? 'active' : '' }}" {{ $activePage=='User'
                ? "data-color='success'" : '' }}>
        <a class="nav-link {{ $parentPage== 'User' ? 'text-white bg-gradient-success active' : 'text-dark' }}"
            {{ $parentPage=='User' ? "data-color='success'" : '' }} href="{{route('admin.users.index')}}">
            <i class="material-icons-round opacity-10">supervisor_account</i>
            <span class="nav-link-text ms-2 ps-1">{{ __('User') }}</span>
        </a>
    </li>
    <li class="nav-item {{ $parentPage == 'Plan' ? 'active' : '' }}" {{ $activePage=='Plan'
                ? "data-color='success'" : '' }}>
        <a class="nav-link {{ $parentPage == 'Plan' ? 'text-white bg-gradient-success active' : 'text-dark' }}"
            {{ $parentPage=='Plan' ? "data-color='success'" : '' }} href="{{route('admin.plans.index')}}">
            <i class="material-icons-round opacity-10">price_change</i>
            <span class="nav-link-text ms-2 ps-1">{{ __('Plan') }}</span>
        </a>
    </li>
    <li class="nav-item {{ $parentPage == 'Role' ? 'active' : '' }}" {{ $activePage=='Role'
                ? "data-color='success'" : '' }}>
        <a class="nav-link {{ $parentPage == 'Role' ? 'text-white bg-gradient-success active' : 'text-dark' }}"
            {{ $parentPage=='Role' ? "data-color='success'" : '' }} href="{{route('admin.roles.index')}}">
            <i class="material-icons-round opacity-10">admin_panel_settings</i>
            <span class="nav-link-text ms-2 ps-1">{{ __('Role') }}</span>
        </a>
    </li>
    <li class="nav-item {{ $parentPage == 'Permission' ? 'active' : '' }}" {{ $activePage=='Permission'
                ? "data-color='success'" : '' }}>
        <a class="nav-link {{ $parentPage == 'Permission' ? 'text-white bg-gradient-success active' : 'text-dark' }}"
            {{ $parentPage=='Permission' ? "data-color='success'" : '' }} href="{{route('admin.permissions.index')}}">
            <i class="material-icons-round opacity-10">settings_accessibility</i>
            <span class="nav-link-text ms-2 ps-1">{{ __('Permission') }}</span>
        </a>
    </li>
    @endcan
    <hr class="horizontal dark mt-0">
    {{-- Dashboard Menu --}}
    <li class="nav-item {{ $activePage == 'dashboard' ? 'active' : '' }}" {{ $activePage=='dashboard'
                    ? "data-color='success'" : '' }}>
        <a class="nav-link {{ $activePage == 'dashboard' ? 'text-white bg-gradient-success active' : 'text-dark' }}"
            {{ $activePage=='dashboard' ? "data-color='success'" : '' }} href="{{route('dashboard')}}">
            <i class="material-icons-round opacity-10">dashboard</i>
            <span class="nav-link-text ms-2 ps-1">{{ __('Dashboard') }}</span>
        </a>
    </li>
    {{-- Farm Menu --}}
    <li class="nav-item ">
        <a data-bs-toggle="collapse" href="#FarmNav" class="nav-link text-dark" aria-controls="FarmNav" role="button"
            {{ ($menuParent=='farm' ) ? ' aria-expanded="true"' : ' aria-expanded="false"' }}>
            <i class="material-icons-round opacity-10">agriculture</i>
            <span class="nav-link-text ms-2 ps-1">{{ __('Farm') }}</span>
        </a>
        <div class="collapse  {{ $menuParent == 'farm' ? 'show' : '' }} " id="FarmNav">
            <ul class="nav ">
                <li class="nav-item {{ $activePage == 'buck' ? 'active' : '' }}">
                    <a class="nav-link {{ $activePage == 'buck' ? 'text-white bg-gradient-success active' : 'text-dark' }}"
                        href="#">
                        <span class="sidenav-mini-icon"> BL </span>
                        <span class="sidenav-normal  ms-2  ps-1"> Buck List </span>
                    </a>
                </li>
                <li class="nav-item {{ $activePage == 'doe' ? 'active' : '' }}">
                    <a class="nav-link {{ $activePage == 'doe' ? 'text-white bg-gradient-success active' : 'text-dark' }}"
                        href="#">
                        <span class="sidenav-mini-icon"> DL </span>
                        <span class="sidenav-normal  ms-2  ps-1"> Doe List </span>
                    </a>
                </li>
                <li class="nav-item {{ $activePage == 'livestock' ? 'active' : '' }}">
                    <a class="nav-link {{ $activePage == 'livestock' ? 'text-white bg-gradient-success active' : 'text-dark' }}"
                        href="#">
                        <span class="sidenav-mini-icon"> L </span>
                        <span class="sidenav-normal  ms-2  ps-1"> Livestock </span>
                    </a>
                </li>
                <li class="nav-item {{ $activePage == 'breeding' ? 'active' : '' }}">
                    <a class="nav-link {{ $activePage == 'breeding' ? 'text-white bg-gradient-success active' : 'text-dark' }}"
                        href="#">
                        <span class="sidenav-mini-icon"> B </span>
                        <span class="sidenav-normal  ms-2  ps-1"> Breeding </span>
                    </a>
                </li>
                <li class="nav-item {{ $activePage == 'kindlingRecord' ? 'active' : '' }}">
                    <a class="nav-link {{ $activePage == 'kindlingRecord' ? 'text-white bg-gradient-success active' : 'text-dark' }}"
                        href="#">
                        <span class="sidenav-mini-icon"> KR </span>
                        <span class="sidenav-normal  ms-2  ps-1"> Kindling Record </span>
                    </a>
                </li>
            </ul>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" href="#" target="_blank">
            <i
                class="material-icons-round {% if page.brand == 'RTL' %}ms-2{% else %} me-2{% endif %} opacity-10">receipt_long</i>
            <span class="nav-link-text text-dark ms-2 ps-1">Changelog</span>
        </a>
    </li>
    </ul>
    </div>
</aside>