routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\SignUpController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Teamwork\AuthController;
use App\Http\Controllers\Teamwork\TeamController;
use App\Http\Controllers\Admin\AdminPlanController;
use App\Http\Controllers\Teamwork\TeamRoleController;
use App\Http\Controllers\Admin\AdminPaymentController;
use App\Http\Controllers\Teamwork\TeamMemberController;
use App\Http\Controllers\Admin\UserController as AdminUserController;
use App\Http\Controllers\Admin\RoleController as AdminRoleController;
use App\Http\Controllers\Admin\PermissionController as AdminPermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::view('dashboard', 'dashboard')
	->name('dashboard')
	->middleware(['auth', 'verified']);

// Route::get('/profile/user', function () {
//     return view('profile.show');
// })->name('profile.show');

// Route::resource('user', ProfileController::class);

Route::get('/signup', [SignUpController::class, 'index'])->name('signup');
Route::group(['middleware' => ['auth'],'prefix' => 'signup'],function () {

    Route::get('/review/{id}', [SignUpController::class, 'review'])->name('signup.review');
    Route::get('/pay/{payment_link}', [SignUpController::class, 'pay'])->name('signup.pay');
    Route::post('/go/{payment_gateway}', [SignUpController::class, 'go'])->name('signup.go');
    Route::post('/thankyou/{payment_gateway}', [SignUpController::class, 'thankyou'])->name('signup.thankyou');
    Route::get('/thankyou/{payment_gateway}', [SignUpController::class, 'thankyou']);
    Route::get('/callback/{payment_gateway}', [SignUpController::class, 'callback'])->name('signup.callback');
    Route::post('/callback/{payment_gateway}', [SignUpController::class, 'callback']);


});

// Regular users
Route::group(['middleware' => ['auth'],'prefix' => 'users'], function () {

    Route::get('/profile/{user}', [ProfileController::class, 'show'])->name('user-profile.show');
    Route::put('/profile/{user}/edit', [ProfileController::class, 'update'])->name('user-profile.update');

    Route::resource('plans', PlanController::class);
    Route::resource('payment', PaymentController::class);
});


/**
 * Admin routes
 */
Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' =>'admin.'], function () {

    Route::resource('plans', AdminPlanController::class);
    Route::resource('users', AdminUserController::class);

    Route::resource('roles', AdminRoleController::class);
    Route::resource('permissions', AdminPermissionController::class);
});


/**
 * Teamwork Roles & Permission routes
 */
Route::group(['middleware' => ['auth'], 'prefix' => 'teams', 'as' => 'teams.'], function ()
{
    Route::resource('roles', TeamRoleController::class);
    Route::resource('permissions', TeamRoleController::class);
});

/**
 * Teamwork routes
 */
Route::group(['middleware' => ['auth'], 'prefix' => 'teams', 'namespace' => 'Teamwork'], function()
{
    Route::get('/', [TeamController::class, 'index'])->name('teams.index');
    Route::get('create', [TeamController::class, 'create'])->name('teams.create');
    Route::get('/{id}', [TeamController::class, 'show'])->name('teams.show')->can('update');
    Route::post('teams', [TeamController::class, 'store'])->name('teams.store');
    Route::get('edit/{id}', [TeamController::class, 'edit'])->name('teams.edit')->can('update');
    Route::put('edit/{id}', [TeamController::class, 'update'])->name('teams.update')->can('update');
    Route::delete('destroy/{id}', [TeamController::class, 'destroy'])->name('teams.destroy')->can('delete');
    Route::get('switch/{id}', [TeamController::class, 'switchTeam'])->name('teams.switch');

    Route::get('members/{id}', [TeamMemberController::class, 'show'])->name('teams.members.show');
    Route::get('members/resend/{invite_id}', [TeamMemberController::class, 'resendInvite'])->name('teams.members.resend_invite');
    Route::post('members/{id}', [TeamMemberController::class, 'invite'])->name('teams.members.invite');
    Route::delete('members/{id}/{user_id}', [TeamMemberController::class, 'destroy'])->name('teams.members.destroy');

    Route::get('accept/{token}', [AuthController::class, 'acceptInvite'])->name('teams.accept_invite');
});

app/Models/Plan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Plan extends Model
{
    use HasFactory;

    protected $fillable =[
        'name',
        'price',
        'duration',
    ];

    public function getMoneyPriceAttribute()
    {
        return 'RM ' . number_format( ($this->price / 100), 2, '.', '' );
    }

    public function getPlanPriceAttribute()
    {
        return number_format( ($this->price / 100), 2, '.', '' );
    }
}

app/Http/Controllers/PlanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Plan;
use App\Http\Requests\StorePlanRequest;
use App\Http\Requests\UpdatePlanRequest;

class PlanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StorePlanRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePlanRequest $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Plan  $plan
     * @return \Illuminate\Http\Response
     */
    public function show(Plan $plan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Plan  $plan
     * @return \Illuminate\Http\Response
     */
    public function edit(Plan $plan)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdatePlanRequest  $request
     * @param  \App\Models\Plan  $plan
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePlanRequest $request, Plan $plan)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Plan  $plan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Plan $plan)
    {
        //
    }
}

resources/views/admin/plans/create.blade.php
@extends('layouts.private',[
'activePage' => 'planCreate',
'parentPage' => 'Plan',
'menuParent' => 'admin.plans.index',
'title' => __('Create Plans')
])

@section('content')
<div class="container-fluid py-4">
    <div class="row mt-4">
        <div class="col-lg-9 col-12 mx-auto position-relative">
            <div class="card">
                <div class="card-header p-3 pt-2">
                    <div
                        class="icon icon-lg icon-shape bg-gradient-success shadow text-center border-radius-xl mt-n4 me-3 float-start">
                        <i class="material-icons opacity-10">groups</i>
                    </div>
                    <h6 class="mb-0">{{__('Create Plan')}}</h6>
                </div>
                <div class="card-body pt-2">
                    <form class="form-horizontal" method="post" action="{{route('admin.plans.store')}}">
                        @csrf
                        <div class="form-group @error('name') has-error text-danger @enderror">
                            <div class="input-group input-group-static">
                                <label for="planName">{{__('Plan Name')}}</label>
                                <input type="text" class="form-control" id="planName" name="name"
                                    value="{{ old('name') }}">
                                @error('name')
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group mt-4 @error('price') has-error text-danger @enderror">
                            <div class="input-group input-group-static">
                                <label for="planPrice">{{__('Plan price')}}</label>
                                <input type="number" min="0" max="99999" step="0.01" class="form-control" id="planPrice"
                                    name="price" value="{{ old('price') }}">
                                @error('price')
                                <span class="help-block">
                                    <strong>{{ $errors->first('price') }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group mt-4 @error('duration') has-error text-danger @enderror">
                            <div class="input-group input-group-static">
                                <label for="planDuration">{{__('Plan Duration')}}</label>
                                <input type="number" min="1" max="99999" step="1" class="form-control" id="planDuration"
                                    name="duration" value="{{ old('duration') }}">
                                @error('duration')
                                <span class="help-block">
                                    <strong>{{ $errors->first('duration') }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="d-flex justify-content-end mt-4">
                            {{-- <button type="button" name="button" class="btn btn-light m-0" href=""></button> --}}
                            <a href="{{route('admin.plans.index')}}" class="btn btn-light m-0">{{__('Cancel')}}</a>
                            <button type="Submit" name="button" class="btn bg-gradient-success m-0 ms-2">{{__('Create
                                Plan')}}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {{-- @include('layouts.footers.auth') --}}
</div>
@endsection

resources/views/admin/plans/index.blade.php
@extends('layouts.private',[
'activePage' => 'planIndex',
'parentPage' => 'Plan',
'menuParent' => '',
'title' => __('Plans')
])
@section('content')
<div class="container-fluid py-4">
    <section class="py-3">
        @if( session('success') )
        @include('layouts.alerts.feedback')
        @endif
        <div class="row mb-4 mb-md-0">
            <div class="col-md-8 me-auto my-auto text-left">
                <h5>List of All Your Plans</h5>
                <p>You can see all your plans here. <br> You may edit, view or switch plan from this page.</p>

            </div>
            <div class="col-lg-4 col-md-12 my-auto text-end">
                {{-- <button type="button" class="btn bg-gradient-primary mb-0 mt-0 mt-md-n9 mt-lg-0"
                    href="{{route('admin.plans.create')}}">

                </button> --}}
                <a href="{{route('admin.plans.create')}}" class="btn bg-gradient-warning mb-0 mt-0 mt-md-n9 mt-lg-0">
                    <i class="material-icons text-white position-relative text-md pe-2">add</i>{{__('Create Plan')}}
                </a>
            </div>
        </div>

        <div class="row mt-lg-4 mt-2">
            @foreach ($plans as $plan)
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card">
                    <div class="card-body p-3">
                        <div class="d-flex mt-n2">
                            {{-- <div class="avatar avatar-xl bg-gradient-dark border-radius-xl p-2 mt-n4">
                                <img src="../../../assets/img/small-logos/logo-slack.svg" alt="slack_logo">
                            </div> --}}
                            <h6 class="mb-0">{{$plan->name}}</h6>
                            {{-- <div class="ms-3 my-auto">
                                <div class="avatar-group">
                                    <a href="javascript:;" class="avatar avatar-xs rounded-circle"
                                        data-bs-toggle="tooltip" data-original-title="Jessica Rowland">
                                        <img alt="Image placeholder" src="../../../assets/img/plan-3.jpg" class="">
                                    </a>
                                    <a href="javascript:;" class="avatar avatar-xs rounded-circle"
                                        data-bs-toggle="tooltip" data-original-title="Audrey Love">
                                        <img alt="Image placeholder" src="../../../assets/img/plan-4.jpg"
                                            class="rounded-circle">
                                    </a>
                                    <a href="javascript:;" class="avatar avatar-xs rounded-circle"
                                        data-bs-toggle="tooltip" data-original-title="Michael Lewis">
                                        <img alt="Image placeholder" src="../../../assets/img/plan-2.jpg"
                                            class="rounded-circle">
                                    </a>
                                    <a href="javascript:;" class="avatar avatar-xs rounded-circle"
                                        data-bs-toggle="tooltip" data-original-title="Jessica Rowland">
                                        <img alt="Image placeholder" src="../../../assets/img/plan-3.jpg" class="">
                                    </a>
                                    <a href="javascript:;" class="avatar avatar-xs rounded-circle"
                                        data-bs-toggle="tooltip" data-original-title="Audrey Love">
                                        <img alt="Image placeholder" src="../../../assets/img/plan-4.jpg"
                                            class="rounded-circle">
                                    </a>
                                </div>
                            </div> --}}
                            <div class="ms-auto">
                                <div class="dropdown">
                                    <button class="btn btn-link text-secondary ps-0 pe-2" id="navbarDropdownMenuLink"
                                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-ellipsis-v text-lg"></i>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-end me-sm-n4 me-n3"
                                        aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" href="{{route('admin.plans.show', $plan->id)}}"><i
                                                class="fa fa-pencil"></i> Edit</a>
                                        {{-- <a class="dropdown-item" href="{{route('plans.destroy', $plan)}}">
                                            <i class="fa fa-trash-o"></i>{{__('Delete')}}
                                            <form style="display: inline-block;"
                                                action="{{route('plans.destroy', $plan)}}" method="post"
                                                class="btn btn-sm btn-default">
                                                @csrf
                                                <input type="hidden" name="_method" value="DELETE" />
                                            </form> --}}
                                            {{-- TODO:Make a modal --}}
                                            {{-- <a class="dropdown-item" href="{{route('plans.edit', $plan)}}"><i
                                                    class="fa fa-pencil"></i> Edit</a> --}}
                                            <a class="dropdown-item"
                                                href="{{ route('admin.plans.destroy', $plan->id) }}" onclick="event.preventDefault();
                                                     document.getElementById('delete-form').submit();"><i
                                                    class="fa fa-trash-o"></i>
                                                {{__('Delete
                                                Plans')}}</a>
                                            <form id="delete-form"
                                                action="{{ route('admin.plans.destroy', $plan->id) }}" method="POST"
                                                class="d-none">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <p class="text-sm mt-3"> Price:
                            {{$plan->money_price}}
                        </p>
                        <p class="text-sm mt-3"> Duration:
                            {{$plan->duration}} Days
                        </p>
                    </div>
                </div>
            </div>
            @endforeach
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100 ">
                    <div class="card-body d-flex flex-column justify-content-center text-center">
                        <a href="{{route('admin.plans.create')}}" class="mb-1 mt-1 mt-md-n9 mt-lg-0 text-center">
                            <i class="material-icons text-secondary">group_add</i>
                            <h5 class="text-secondary">
                                {{__('Create Plan')}}
                            </h5>
                        </a>
                        <br />
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-lg-4 mt-2">

        </div>
    </section>
    @include('layouts.footers.auth')
</div>
@endsection

resources/views/admin/plans/show.blade.php
@extends('layouts.private',[
'activePage' => 'planEdit',
'parentPage' => 'Plan',
'menuParent' => 'admin.plans.index',
'title' => __('Plans')
])

@section('content')
<div class="container-fluid py-4">
    <div class="row mt-4">
        <div class="col-lg-9 col-12 mx-auto position-relative">
            <div class="card">
                <div class="card-header p-3 pt-2">
                    <div
                        class="icon icon-lg icon-shape bg-gradient-success shadow text-center border-radius-xl mt-n4 me-3 float-start">
                        <i class="material-icons opacity-10">groups</i>
                    </div>
                    <h6 class="mb-0">{{__('Edit Plan')}} {{$plan->name}}</h6>
                </div>
                <div class="card-body pt-2">
                    <form class="form-horizontal" method="post" action="
                    {{-- {{route('admin.plans.update', $plan)}} --}}
                    ">
                        @method('PUT')
                        @csrf
                        <div class="form-group @error('name') has-error text-danger @enderror">
                            <div class="input-group input-group-static">
                                <label for="planName">{{__('Plan Name')}}</label>
                                <input type="text" class="form-control" id="planName" name="name"
                                    value="{{ old('name', $plan->name) }}">
                                @error('name')
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group mt-4 @error('price') has-error text-danger @enderror">
                            <div class="input-group input-group-static">
                                <label for="planPrice">{{__('Plan price')}}</label>
                                <input type="number" class="form-control" id="planPrice" name="price"
                                    value="{{ old('price', $plan->money_price) }}">
                                @error('price')
                                <span class="help-block">
                                    <strong>{{ $errors->first('price') }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group mt-4 @error('duration') has-error text-danger @enderror">
                            <div class="input-group input-group-static">
                                <label for="planDuration">{{__('Plan Duration')}}</label>
                                <input type="number" class="form-control" id="planDuration" name="duration"
                                    value="{{ old('duration', $plan->duration) }}">
                                @error('duration')
                                <span class="help-block">
                                    <strong>{{ $errors->first('duration') }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="d-flex justify-content-end mt-4">
                            <a href="{{route('admin.plans.index', $plan)}}"
                                class="btn btn-light m-0">{{__('Cancel')}}</a>
                            <button type="Submit" name="button" class="btn bg-gradient-success m-0 ms-2"><i
                                    class="fa fa-btn fa-save"></i>{{__('SAve')}}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {{-- @include('layouts.footers.auth') --}}
</div>
@endsection